[tasks.gen-c-bindings]
install_crate = "cbindgen"
command = "cbindgen"
args = ["-c", "cbindgen.toml", "-o", "target/release/tts-rs.h"]

[tasks.build-android-example]
script = [
    "cd examples/android",
    "./gradlew assembleDebug",
]

[tasks.run-android-example]
script = [
    "cd examples/android",
    "./gradlew runDebug",
]

[tasks.log-android]
command = "adb"
args = ["logcat", "RustStdoutStderr:D", "*:S"]
