[tasks.install-cargo-apk]
install_crate = { crate_name = "cargo-apk", binary = "cargo-apk", test_arg = "--help" }

[tasks.build-android-example]
dependencies = ["install-cargo-apk"]
command = "cargo"
args = ["apk", "build", "--example", "android_hello_world"]

[tasks.run-android-example]
dependencies = ["install-cargo-apk"]
command = "cargo"
args = ["apk", "run", "--example", "android_hello_world"]

# `tts` is the example's logging tag.
[tasks.log-android]
command = "adb"
args = ["logcat", "-s", "tts"]

[tasks.install-trunk]
install_crate = { crate_name = "trunk", binary = "trunk", test_arg = "--help" }

[tasks.install-wasm-bindgen-cli]
install_crate = { crate_name = "wasm-bindgen-cli", binary = "wasm-bindgen", test_arg = "--help" }

[tasks.build-web-example]
dependencies = ["install-trunk", "install-wasm-bindgen-cli"]
cwd = "examples/web"
command = "trunk"
args = ["build"]

[tasks.run-web-example]
dependencies = ["install-trunk", "install-wasm-bindgen-cli"]
cwd = "examples/web"
command = "trunk"
args = ["serve"]