[package]
name = "web"
version = "0.1.0"
authors = ["Nolan Darilek <nolan@thewordnerd.info>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seed = "0.10"
tracing-wasm = "0.2"
tts = { path = "../.." }
uuid = { version = "*", features = ["js"] }
# Needed because seed doesn't enable this feature
