cache = [
    { inputs = [
        ".devcontainer/postCreate.sh",
    ], paths = [
        "/root/.local",
        "/root/.android",
        "/usr/local/android/build-tools",
        "/usr/local/android/ndk",
        "/usr/local/android/platforms",
        "/usr/local/android/system-images",
        "/usr/local/cargo/bin",
    ] },
    { inputs = [
        "Cargo.lock",
        "Cargo.toml",
    ], paths = [
        "target",
    ] },
    { inputs = [
        "examples/web/Cargo.lock",
        "examples/web/Cargo.toml",
    ], paths = [
        "examples/web/target",
    ] },
    { paths = [
        "/usr/local/cargo/registry",
    ] },
]

script = ".radicle/ci.sh"
